export const CREATE_SESSION = "CREATE_SESSION";
export const DESTROY_SESSION = "DESTROY_SESSION";



//THEME TOGGLE
export const TOGGLE_THEME = "TOGGLE_THEME";

//FOR ERROR IN AUTH PROCESS
export const RESPONSE_SUCCESS = "RESPONSE_SUCCESS";
export const RESPONSE_ERROR = "RESPONSE_ERROR";
export const RESPONSE_CLEAR = "RESPONSE_CLEAR";
//FOR FETCHING AND REMOVING USER
export const FETCH_USER = "FETCH_USER";
export const REMOVE_USER = "REMOVE_USER";
export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE";

//FOR CARDS ACTION
export const FETCH_CARDS = "FETCH_CARDS";
export const ADD_NEW_CARD = "ADD_NEW_CARD";
export const EDIT_CARD = "EDIT_CARD";
export const DELETE_CARD = "DELETE_CARD";

//FOR LOGINIDS ACTIONS
export const ADD_NEW_LOGIN_ID = "ADD_NEW_LOGIN_ID";
export const FETCH_LOGIN_IDS = "FETCH_LOGIN_IDS";
export const EDIT_LOGIN_ID = "EDIT_LOGIN_ID";
export const DELETE_LOGIN_ID = "DELETE_LOGIN_ID";

//FOR ADDING AND REMOVING  TO AND FROM FAVORITES
export const ADD_TO_FAVOURITE_LOGINS = "ADD_TO_FAVOURITE_LOGINS";
export const REMOVE_FROM_FAVOURITE_LOGINS = "REMOVE_FROM_FAVOURITE_LOGINS";
export const ADD_TO_FAVOURITE_CARDS = "ADD_TO_FAVOURITE_CARDS";
export const REMOVE_FROM_FAVOURITE_CARDS = "REMOVE_FROM_FAVOURITE_CARDS";
export const ADD_TO_FAVOURITE_DOCS = "ADD_TO_FAVOURITE_DOCS";
export const REMOVE_FROM_FAVOURITE_DOCS = "REMOVE_FROM_FAVOURITE_DOCS";

//FOR TOGGLING IS_FAVOURITE
export const TOGGLE_LOGINS_IS_FAV = "TOGGLE_LOGINS_IS_FAV";
export const TOGGLE_CARDS_IS_FAV = "TOGGLE_CARDS_IS_FAV";
export const TOGGLE_DOCS_IS_FAV = "TOGGLE_DOCS_IS_FAV";

//FOR DOCS ACTIONS
export const FETCH_DOCS = "FETCH_DOCS";
export const ADD_NEW_DOC = "ADD_NEW_DOC";
export const EDIT_DOC = "EDIT_DOC";
export const DELETE_DOC = "DELETE_DOC";

//FOR LOADING POPUP
export const LOADING_SET = "LOADING_SET";
export const LOADING_START = "LOADING_START";
export const LOADING_END = "LOADING_END";
export const CARDS_FETCH_LOADING = "CARDS_FETCH_LOADING";
export const LOGINIDS_FETCH_LOADING = "LOGINIDS_FETCH_LOADING";
export const DOCS_FETCH_LOADING = "DOCS_FETCH_LOADING";

//FOR LOGIN AND LOGOUT
export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGOUT = "USER_LOGOUT";

//FOR TOKEN ADD  AND REMOVE
export const TOKEN_SET = "TOKEN_SET";
export const TOKEN_REMOVE = "TOKEN_REMOVE ";

//FOR ERROR AND SUCCESS NOTIFICATION
export const ERROR_MESSAGE = "ERROR_MESSAGE";
export const SUCCESS_MESSAGE = "SUCCESS_MESSAGE";
export const CLEAR_ERROR = "CLEAR_ERROR";
export const CLEAR_SUCCESS = "CLEAR_SUCCESS";

//FOR CRUD OPERATIONS
export const OPERATION_START = "OPERATION_START";
export const OPERATION_END = "OPERATION_END";

//FOR PROCESS
export const PROCESS_START = "PROCESS_START";
export const PROCESS_END = "PROCESS_END";
export const PROCESS_CLEAR = "PROCESS_CLEAR";
//FOR RECENT ACTIVITY LIST
export const ADD_ACTIVITY = "ADD_ACTIVITY";
export const FETCH_ACTIVITIES = "FETCH_ACTIVITIES";

//FOR SEARCHI_TEM CRUD
export const EDIT_SEARCH_ITEM = "EDIT_SEARCH_ITEM";
export const TOGGLE_SEARCH_FAV = "TOGGLE_SEARCH_FAV";
export const DELETE_SEARCH_ITEM = "DELETE_SEARCH_ITEM";

//______________________________________________________________________________
//
//
//
//
//
//
//___NOT IN USE__________________________________________________________________________________________________________________
// export const GET_USER = "GET_USER";
// export const LOGIN_SUCCESSFUL = "LOGIN_SUCCESSFUL";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const AUTH = "AUTH";
export const LOGIN_START = "LOGIN_START";
export const SIGNUP_FAILED = "SIGNUP_FAILED";
export const SIGNUP_START = "SIGNUP_START";

export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT = "LOGOUT";
export const ADD_NEW_CARD_FAILED = "ADD_NEW_CARD_FAILED";
export const ADD_NEW_USER = "ADD_NEW_USER";

export const SEARCH = "SEARCH";
